### ISSUE TITLE
Is the upgrade to Java17 necessary?

### ISSUE THREAD

**Issue by pe1uca** [DraqueT/PolyGlot#1034]
In the commit eacaa043c04d310c3b7943e4e07c36ca1e8d1840 the version of java was upgraded from 14 to 17.  

Is there a necessity to make this upgrade?  

This commit introduces a syntax change available in newer versions that is incompatible to be compiled with android.  
This has been the only issue right now, runtime differences are still to be checked.
```java
-        if (comp instanceof DictCore) {
-            DictCore compCore = (DictCore)comp;
+        if (comp instanceof DictCore compCore) {
```

**Comment by DraqueT** [comment]
The Java 17 syntax isn’t necessary, although I’m moving to J17 as it’s an LTS release. Feel free to make PRs that remove syntax for anything J9+ in the core classes that you need access to. I will keep from using any moving forward from here so that it will compile normally for you in a J8 environment, and swap back anywhere I notice it.

**Comment by DraqueT** [comment]
Closing this one for now, but please toss me a line if you want to discuss more. I would love to chat in real time or something. ^^
