### ISSUE TITLE
[BETA] PDF: some characters do not appear at all on certain places

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1051]
Polyglot version: Windows BETA from 24th November 2021

Unrendered characters: `ě ů č ď ň ř ť ť` (and probably more I didn't test)

places:
- table of contents
- local language word in lexicon part

note: after testing Charil SIL font online, it seems it might be font's fault

**Comment by DraqueT** [comment]
Double checked this  and that is the case. I chose Charis because its is overall pretty good with character rendering, but no font is perfect. As it stands, PolyGlot can check to see whether all characters render correctly with the Tools->Check Language feature, and any words that contain problems will be brought back in the result dialogue.

**Comment by TrapinchO** [comment]
Still appears to me. Both conlang and local fonts were set to "arial" and "calibri", characters are still missing. "Check language" shows only errors related to ungenerated pronunciations for my temporary lexicon entries (which is correct).

**Comment by TrapinchO** [comment]
Please reopen.

Also, the pdf font seems to be independent on the font choice in polyglot. (which causes the characters to be missing)

**Comment by DraqueT** [comment]
Well shoot. This might be an OS specific issue. You're running Windows 10, right? I'll see if I can't reproduce it in a VM.

**Comment by TrapinchO** [comment]
yeah, windows 10

**Comment by DraqueT** [comment]
Alright, found the cause of this. The testing process I used didn't match PolyGlot's actual interaction with the library... all fields were being set to the local language font... which was *never passed in*. X|
