### ISSUE TITLE
error code 2318

### ISSUE THREAD

**Issue by eliskk** [DraqueT/PolyGlot#1091]
sry if there is a file w error codes written in but i keep getting error 2318 what is that

**Comment by DraqueT** [comment]
Thanks for taking the time to write this! 

Could you please post a screenshot and general description of how you made that error appear? PolyGlot does not use error codes, so I'm not sure what might be causing that.

**Comment by DraqueT** [comment]
It seems like this is actually a Java error rather than something coming from PolyGlot. There are a few things that can cause it. It's possible that you have installed PolyGlot to a folder which you no longer have access to. It's possible that your system is running very low on memory. It's possible that your computer has no disk space left, so it cannot create virtual memory when it is needed.

So try reinstalling PolyGlot (just open the installer again and do a repair install) and generally see if any of those cleanups for your system do the trick. Good luck and I hope this helps!
