### ISSUE TITLE
Ligatures stop working when program is restarted.

### ISSUE THREAD

**Issue by HappyHippo77** [DraqueT/PolyGlot#1092]
I have a font that has some basic ligatures and substitutions, which combine things like "th" and "rr" into single letters. However, when I restart PolyGlot, they all get replaced by the separate glyphs, in all parts of the program. The only way to fix it is to reimport the font.

**Comment by DraqueT** [comment]
Heyo! Thanks for reporting!

This is actually a known bug which is fixed in the newest beta for PolyGlot (also downloadable on the main site). Version 3.5 is going to be released within the next few weeks, so you can either jump on the beta now or wait for the official release which cleans up a few last things. 

Thanks for using PolyGlot, and I hope you're enjoying it!
