### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by Brooks369** [DraqueT/PolyGlot#1168]
Can the app develop an installable font of the language i create?

**Comment by DraqueT** [comment]
Heyo! Thanks for posting and making a suggestion!

So on one hand, I don't think that I am going to implement this. But on the *other* hand... the whole reason I'm not going to is because there are already awesome font constructing tools that exist for free and which create PolyGlot compatible fonts. There's no way that anything that I implement directly in PolyGlot would be as good as those.

Check out Fontstruct and Font Forge. Both are 100% free and will do exactly what you need! :3
