### ISSUE TITLE
[suggestion] regex change

### ISSUE THREAD

**Issue by SpartanCreeper** [DraqueT/PolyGlot#1176]
maybe change the regex entirely? lexurgy has an amazing system in which they have less symbols and easier over all, they work with classes etc but that isnt necessary, u could do something like instead of "$" u have "_ $", in which "_" resembles the place and "$" the word boundry, so "$ _" is the same as "^", u could add things like regrex: `_ [a, i, u]? $`; replacement: "m" which is similar to the regex, but far easier (tho i still dont know how to to do that with the regrex)
lexurgy seems to be a simplified version of the regex u r using, so itd be amazing if ud add that
how lexurgy works: https://www.meamoria.com/lexurgy/html/sc-tutorial.html (it is a sound change generator, but a big part could be used here)

another thing id like to see being added is reduplication as a grammatical function, which would be signalled as "~"
for example `$~[p, t, k][a, i, u]`, this would look if theres a p, t or k in the word followed by a, i or u, if so then it wou reduplicate the word
`$~{$[p, t, k][a, i, u]}` would be the same but the word has to start with it instead

**Comment by DraqueT** [comment]
Heyo! I am thinking about integrating Lexurgy, as I mentioned in another ticket. The changes would be exclusively for the language evolution portion of PolyGlot though, as Regex is pretty heavily integrated and useful all over the place in the rest of the program.

I'm closing this ticket because the other is the one I'll be using to keep track of Lexurgy integration (presuming the original author gives me their blessing to do so)

**Comment by SpartanCreeper** [comment]
thx, but i still think it could be useful for making the conjugations, and if u r adding lexurgy than it could uniform everything more, but alr thx for (at least trying to) intergrate lexurgy
