### ISSUE TITLE
Illegal clusters functionality

### ISSUE THREAD

**Issue by Yoloyer27** [DraqueT/PolyGlot#1186]
Illegal clusters don't seem to work across multiple syllables. I've setup my types so that some clusters may appear between CVC syllables that aren't allowed in my phonotactics. I've put those in the illegal clusters box but they still appear in generated words. Is this intended?

**Comment by DraqueT** [comment]
Thanks for taking the time to report this! This is actually a known bug, which is fixed in the latest Beta release of PolyGlot. Click below and download a beta copy and you'll find this has been addressed. I am hoping to make a release of PolyGlot which includes this within the next month or so.

https://draquet.github.io/PolyGlot/

**Comment by DraqueT** [comment]
Closing this for now, please reopen if the beta does not fix it for you.
