### ISSUE TITLE
[suggestion] Ability to change font for the Lexical class Free text value

### ISSUE THREAD

**Issue by sombra-glaze** [DraqueT/PolyGlot#1224]
![image](https://user-images.githubusercontent.com/93852837/208083446-4cbb36e2-0dce-4f7f-9a59-fa4afb33c075.png)

Hi :) I'm new to PolyGlot and I'm really liking it, it's super cool, I've just come across one small issue so I thought I'd make a suggestion

My script has quite a bit of historical spelling (and some of my scripts are abjads where you can't really get the whole pronunciation from the glyphs) so instead of generating the romanization through the script I wanted to insert it manually, I added a Lexical class called "Romanization" but I realized it uses the conlang font for that text field, so instead I will use the definition window to input the romanization, but I think it'd be a good addition if PolyGlot allowed you to change the font that you want to use for the free text value, or if it already does I didn't find how in the help page :p

**Comment by DraqueT** [comment]
Heyo! What you are seeing there is actually a bug which has been fixed in the latest beta! Please check it out in the link below. Also, sorry for taking a while to get back to you here! If you still have issues with this, please feel free to reply here and I will see it.

https://draquet.github.io/PolyGlot/
