### ISSUE TITLE
is the project still active?

### ISSUE THREAD

**Issue by crimsonblue17** [DraqueT/PolyGlot#1338]
a concerning trend with this repo is that it does not seem to be active anymore. the last closed issue (excluding #1336, which was closed by the creator) was 4 months ago (the last one that was not typos or documentation was 6 months), the last commit made to the code base was made 5 months ago, the last merged pull request was made 7 months ago, the copyright date on the license is still 2023, and the copyright date on the website is still 2022.  

if the project is not active, i have started work on a fork, [Wordsmith](https://codeberg.org/crimsonblue17/wordsmith), where i expect to continue development work. however, before dedicating time and effort to maintaining a fork, i would like to first verify if the project is active or not.

**Comment by DraqueT** [comment]
This project is still alive, but I am likely only going to make one more major version update. There have been a ton of changes since the last major release that I want to get out there, and there are a few nasty bugs that I need to quash, but after that, I think this project is going to be mostly "done" for a while. I have a game project I'm putting most of my free time into at this point, which is eating up the time I had previously spent on PolyGlot.

In the mean time, the newest available Beta has quite a few fixes and a lot of new features if you haven't checked that out yet!

**Comment by crimsonblue17** [comment]
ok. i still plan to continue development on Wordsmith, as i plan to move in a different direction with the project, with some more radical changes, unless you have any objections. thank you for clearing up the situation with the project and i wish you luck in whatever you work on.

**Comment by DraqueT** [comment]
I am open to PRs to the main repo here as well. Please feel free to continue the fork obviously, but if we minimize the differences, it will ensure that anything I add to this primary branch in the future, you will be easily able to pull and include in yours as well. If you want to chat or anything let me know and we can open some higher bandwidth communication.
