### ISSUE TITLE
Revise Readme: Arch Linux Font Rendering

### ISSUE THREAD

**Issue by kdelwat** [DraqueT/PolyGlot#176]
On Arch Linux 4.0.5-1 with the bspwm window manager, fonts are pixelated and rendered incorrectly. The attached photo does not show the problem to its full extent, but is a reasonable indication.
![2015-06-12-171609_1366x768_scrot](https://cloud.githubusercontent.com/assets/1031518/8125196/f81e95bc-1126-11e5-9b46-ac770ac59413.png)

**Comment by DraqueT** [comment]
Thanks for the bug report and the screen shot! I'll give this a try in the Linux distros that I have virtual environments for. If this is a bug specific to your build with that particular window manager though, it might be a while before I can get to the bug.

Conversely, I am moving away from Java 1.6 up to Java 1.7 due to getting way too frustrating due to bugs exactly like this one (platform specific). Hopefully that will clear up your problem once PolyGlot 1.0 is released.

**Comment by DraqueT** [comment]
Integrate suggestions in this (https://wiki.archlinux.org/index.php/Java_Runtime_Environment_fonts) article to readme. Font rendering can be beautified based on system settings in Arch Linux if it looks unpleasant or pixilated.

**Comment by DraqueT** [comment]
Done.
