### ISSUE TITLE
alphabet and pronunciation list in lang properties become uneditable

### ISSUE THREAD

**Issue by DraqueT** [DraqueT/PolyGlot#250]
Pretty much just what the description says. Having trouble tracking it down, but have seen it myself at least once.

UPDATE: This turns out to be because of an error that saves a PGD with the font size (of which there are two places to save it... need to address that) as 0. This messes with the ability to save, and other functions. Make a check that prevents it from saving as 0, and consider removing the superfluous font size variable entirely.

**Comment by JukeBoxHeroTP** [comment]
This bug seems to only be in effect when a specific .pgd file is open. Whatever the cause is, it seems to affect some other things as well, such as certain entry boxes being the wrong size(Vertically flat), to where I can't see what is typed in the box. I currently am having this issue with my language file I am working on. I saw the problem both where you mentioned it, and with this Regex box in this window.
![image](https://cloud.githubusercontent.com/assets/10180022/11611032/07c9e17e-9b7e-11e5-8b01-a847765fc4ac.png)
I am also unable to see what I have typed into these Conjugations/Declensions boxes.
![image](https://cloud.githubusercontent.com/assets/10180022/11611043/8b53a2c8-9b7e-11e5-8409-683c7fe7abba.png)
There may be other things this has broken, which I haven't seen yet.  
  
Earlier, I had an error message show up when saving this .pgd, I had to forcible end the Java process, and my small amount of work was not saved, so it may be possible that this has caused it.  
  
Hope this gets fixed soon as it is quite affecting my ability to use the program. I may take a look at this bug myself and see what I can do if I get the time.  
  
Keep up the good work, cheers!

**Comment by JukeBoxHeroTP** [comment]
Ok, so I've had some trouble getting a fork that works and all(I'm a bit new to github and Eclipse was throwing me weird errors), but I have done some looking into the problem by looking at the .pgd file. Trying to figure out how it was formatted, changed it to .txt and saw "PGDictionary.xml". Changed to zip and extracted the xml file.  
  
From here I tried a couple things:  
-Re-zipping the xml, changing .zip to .pgd. Same bugs happening  
-Then I tried copying the text from the .xml into a new .txt file, saving with UTF-8 encoding, and changing file type to .xml. I then zipped that xml, and changed the zip to .pgd. Still having the same bugs.  
  
This last thing which I tried leads me to believe that the problem lies somewhere in the actual code of the xml.  
  
Hope this can help!

**Comment by JukeBoxHeroTP** [comment]
Upon further inspection, this bug seems to happen with any .pgd file which I create, save, and load the file. It is not, however, in effect when I load either of the Example Dictionaries.

**Comment by JukeBoxHeroTP** [comment]
Ah-HA! I've got it. I looked at the xml of the example dictionaries, and found that the font size was 12, where as the font size in ones I saved was 0. Changed my to 12, loaded them up and worked fine. Hit save, it gave me a saving error, and froze for a few seconds, but after that it seemed that I could save and load just fine, without getting the bug again! So it seems the problem is just in when the file gets saved the first time, it just is saving the wrong font size, which messes things up!

**Comment by DraqueT** [comment]
Oh my goodness, thank you for all the work and documentation that you've done here! I'm definitely going to be looking into this and correcting, which will be much, much easier thanks to all the sleuthing that you've put in. Once you changed the font size to something proper, did all of the problems vanish, or just the saving issue?

**Comment by JukeBoxHeroTP** [comment]
I didn't have time to look through everything, but it seemed like everything was back to normal. And no problem, I'm happy to help!

**Comment by JukeBoxHeroTP** [comment]
I noticed that in PropertiesManager.java
https://github.com/DraqueT/PolyGlot/blob/master/src/PolyGlot/ManagersCollections/PropertiesManager.java  
That fontSize is defaulted to 0. If this was instead defaulted to 12 it may fix the issue, since there is no way to edit the font size from within PolyGlot as far as I know.

**Comment by DraqueT** [comment]
Yep! That's what I've been looking at as well. Right now, I'm just tinkering with the whole system and looking to simplify a bit of it. There are some values that are duplicated across multiple values, and that could cause trouble if synchronization doesn't take place properly. Better to just whittle it down a bit.

**Comment by DraqueT** [comment]
This has been resolved. Thanks again for the assist, Juke! :+1:

**Comment by JukeBoxHeroTP** [comment]
No problem! :D
