### ISSUE TITLE
Syllables

### ISSUE THREAD

**Issue by electric-snake** [DraqueT/PolyGlot#406]
Not a quick or easy request by any means, but some kind of system for informing the program about the syllables in a word would be nice, and would enable some handy features, such as allowing the auto-pronunciation guide to take syllables into account, or allow rules regarding syllables in the various auto-generation systems.

**Comment by DraqueT** [comment]
Heyo! As a heads up, this is a fantastic idea! Unfortunately, after I've done some research, it seems like it is not possible. Even given a fully patterned character->IPA transformation, there is no way to be certain of phonographic separation and syllable differentiation even within single dialects of most languages. I could implement something like this anyhow... but that would only serve to ensure that languages created in PolyGlot are less like natural languages than they otherwise would be. X|

I am looking into a good way to implement something in between that would allow users to define syllables after the system has already generated the pronunciation, but this will require some thought.

Again, thank you for all the suggestions! Please continue tossing them my way when you think of them! : 3
