### ISSUE TITLE
Mobile?

### ISSUE THREAD

**Issue by KDG28** [DraqueT/PolyGlot#446]
I would love if you guys made a mobile version of this app. I think it would be very cool to be able to use such a program on the go.

**Comment by DraqueT** [comment]
Hey there! Thank you for the interest in PolyGlot! Unfortunately, it's just little ol' me working on the project in my spare time at the moment (rather than a team or anything), so making  whole 'nother app for it would be difficult. I've been considering looking at a project that would allow a website to do basic interpretation/display of the files, but that itself would be pretty far in the future.

It's open source though, so anyone who wants to snag the language core functionality and put it into a mobile app is welcome to do so! :3
