### ISSUE TITLE
UI does not scale on high DPI on windows 10

### ISSUE THREAD

**Issue by kattla** [DraqueT/PolyGlot#447]
I'm trying to run PolyGlot on a computer with windows 10 and a high DPI screen. In the settings for my computer I've chosen a scaling factor of 150% which makes the text readable in most programs. PolyGlot however does not seem to adhere to this, which makes the interface look small and the text is nearly unreadable.

This is using PolyGlot 2.0

**Comment by DraqueT** [comment]
Adding functionality to allow users to size up default text is a feature that's currently planned. The JVM does not have integration with Windows 10's scaling features, which is why you don't see the changes reflected there.

In the mean time, I'm sorry you're having this trouble! If I find a workaround for you, I'll post it here for you to see.

**Comment by DraqueT** [comment]
As a heads up, I'm only closing this because the fix is covered by ticket #404 . Check that one out if you're interested in following progress on fixing this! :)
