### ISSUE TITLE
Phonology messes up expected behavior when "Recurse Patterns" is checked

### ISSUE THREAD

**Issue by dapperdanman1400** [DraqueT/PolyGlot#511]
I have a word that is spelled: 

> SJjNBk

 The word's IPA pronunciation should be:

> lwed**iː**

However, when I have **Recurse Patterns** set, it outputs the following:

> lwed**eː**

As you can see below, the upper red rule gets applied, then it recurses and (mistakenly) applies the lower red rule. I can get around this by adding/adjusting rules, turning off Recurse Patterns (which breaks my lookahead/lookbehind patterns), but I don't think this should be the expected behavior.

![recurse](https://user-images.githubusercontent.com/19856607/31700806-cbaecbc0-b406-11e7-9bab-8bbda8291736.jpg)

**Comment by DraqueT** [comment]
Thanks for the bug report! I'll take a look at this one and try to see what's up with it.

**Comment by DraqueT** [comment]
Heyo! It took me a while to swing around to this (real life and whatnot), but I was finally able to take a look!

It seems like the problem can be corrected by specifying in the regular expressions to exclude the pattern '"i" from the replacement if it is immediately followed by "ː". The way that the recursion works, it will greedily snatch up anything that matches, rather than presuming not to make a replacement just because it's an element of a previously set character.

I've looked into alternate solutions, but the whole point of the recursion is to allow people to apply transformations to elements of the text string which have already been modified.

I'm going to close the ticket, but if you have any other suggestions or thoughts regarding this functionality, please post them here and I'll read/consider! :3
