### ISSUE TITLE
Resolution Scaling

### ISSUE THREAD

**Issue by Arc6180** [DraqueT/PolyGlot#531]
This is currently a known bug in Java. Support for turning off false DPI scaling reporting to OS is currently just borked.

RELEVANT ORACLE TICKET: https://bugs.openjdk.java.net/browse/JDK-8080153

ORIGINAL USER COMMENT
Teeeny tiny on 4k display.

**Comment by DraqueT** [comment]
There is a partial fix to this one atm. You can go in and change the default font size for menus in the options of PolyGlot, and you can choose the font (including size) for your conlang. I still need to implement the ability to change the local font, but that is coming soon! Ultimately this whole problem comes from the way that Java renders graphics, which is tied to the size of pixels. Still looking for a more elegant solution.

Thank you for the interest in the project, and I hope you're finding the program useful otherwise. ^^

**Comment by DraqueT** [comment]
Hello! Just getting back to you with a more comprehensive fix! This is apparently a problem with Java itself which *does* have a workaround! Check out this link, which should show you how to make it aware of DPI scaling: https://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display

**Comment by DraqueT** [comment]
Seems like Windows 10 running Java 9 will accept the "Dsun.java2d.dpiaware", "false" setting. Need to test in a virtual or on the home Win 10 server. Potential fix in, but currently untested.

**Comment by DraqueT** [comment]
Confirmed that this is fixed.
