### ISSUE TITLE
Can't find PolyGlot.jar

### ISSUE THREAD

**Issue by arthurdejaffre** [DraqueT/PolyGlot#549]
Hello! I don't know if I just missed it but I followed the installation instructions for windows and it went well except I can't find "PolyGlot.jar" that it asks me to doubleclick on.

**Comment by DraqueT** [comment]
Let's see... first off, make sure that you've downloaded the program rather than the source code (https://github.com/DraqueT/PolyGlot/releases/download/2.2/PolyGlot_2.2.zip).

Once that's unzipped into a destination folder, you should be able to double click either the exe file or PolyGlor.jar, which will be right in the root directory. If you're still not seeing it after that let me know and we can figure it out. :)

**Comment by arthurdejaffre** [comment]
Ha! Thanks! I had indeed downloaded the source code and not the program... also just noticed the "releases" tab... that explains it. Thanks a bunch!!

**Comment by DraqueT** [comment]
👍
