### ISSUE TITLE
Declensions not autogenerating

### ISSUE THREAD

**Issue by snorepion** [DraqueT/PolyGlot#553]
I followed the help page word-for-word when creating declensions for verbs and the regexes should be perfectly valid, but the declensions aren't autogenerating in the lexicon even when all fields are filled out. [Here](https://github.com/DraqueT/PolyGlot/files/1905013/Magisava.zip) is the PGD file. Could this have to do with the combining diacritical marks used on certain characters?

Edit: Just checked; the same problem happens on nouns.

**Comment by DraqueT** [comment]
Heyo! Just took a look and I see what the issue here is. Each of your rules has a blank filter value. Just add ".*" to the filter so that it applies universally.

I am also adding an enhancement to make that populate to the value automatically. Most people do not use the filter feature, so it should default to everything.

Hope you're enjoying the program otherwise! :3
