### ISSUE TITLE
Suggestion: Allowing the conlang font to be used in conjugations

### ISSUE THREAD

**Issue by MaofFoam** [DraqueT/PolyGlot#577]
Due to the nature of my conlang, using the roman alphabet, or any other type of romanization does not allow to conjugate the verbs properly (it is due mainly to the story behind the conlang, with characteristics like borrowing letters from other languages and using some of these duplicates when conjugating)

Maybe adding some way to toggle on and off the use of the font used in the lexicon of the conlang when using the conjugation interface, or setting up the conjugation in the parts of speech.

Thanks for making such an awesome tool
Keep up the good work

**Comment by DraqueT** [comment]
This is actually taken care of in the upcoming build! Allowing the default font to be changed was a much requested feature! If this is necessary to your work, please send an email to draquemail@gmail.com and I can hook you up with a prerelease (though word of warning, rereleases are something that I can't offer support for since they're full of unfinished features and fixes).
