### ISSUE TITLE
Problems with saving

### ISSUE THREAD

**Issue by gy1216** [DraqueT/PolyGlot#609]
Hello, I am now using the newest version of Polyglot (2.3.1) and with Java (build 1.8.0_181-b13) on windows 10. 
  It seems that some of the words are gone every time I save the file and re-open it. I tested it. It turned out that there had been originally 137 words in my dictionary and only 114 left when I launched the programme again. 
  Is there anything that I could do to avoid this problem? 
Thank you!

**Comment by DraqueT** [comment]
Thanks for the notification! This is a really serious bug, and I'm working
on it right now. I hope that you didn't lose too much work there, and I'm
looking into getting it corrected at the moment!

Could you jot down any details about what was going on at the time that
this came up that you can remember? Really anything at all would be
helpful. This bug seems to appear randomly, and I have never actually
observed it myself. Thanks, and I will 100% try to help recover lost data
if I'm able!

- Draque

**Comment by DraqueT** [comment]
Getting the error to show up finally... certain files will fail to save
correctly. Each time I see the bug, a random number of words is saved.
Different each time. O_o

- Draque

**Comment by DraqueT** [comment]
Fuuuuck. Welp. Found it at least. Explains why it was running differently
on different machines. : |

[image: image.png]

It was trying to loop and write the XML in parallel, which was freaking the
XML generation nodes out.

- Draque
