### ISSUE TITLE
Selecting Class Values in Conjugation/Declension Setup

### ISSUE THREAD

**Issue by yatenari** [DraqueT/PolyGlot#611]
It is a great help to simplify the conjugation/declension setup to be able to use match by class value, since it not only allows to determine declension systems without having to determine the exact filters for any rule. It certainly makes working out some rules far easier.
However, I am not sure if that is simply not implemented or if it might be a bug - it is possible to select either "all" class values or a single one, but there is no way to select two, for example. For some forms it might be useful to have the ability to choose a different number of class values (i. e. if you have different vowel declensions and consonant declensions, it would be helpful if "all vowel declensions" could be selected in some instances where they might share a form while keeping the distinction of other forms).

It is mostly for convenience, since currently it still works fine if a rule is added for every declension separately, so it is only a suggestion for the future.

**Comment by DraqueT** [comment]
When I was putting this together, I had to decide whether I wanted the check system to be inclusive or exclusive. I decided that because you can easily copy/paste rules by selecting/right clicking, that I would make it exclusive, since that allows for greater granularity of control.

This is why if you go to select a second value of a class, it will deselect the others automatically. : )

**Comment by DraqueT** [comment]
Closing this for now. Feel free to comment/reopen if it's still giving you trouble!
