### ISSUE TITLE
Search Interface Crashes

### ISSUE THREAD

**Issue by miacomet** [DraqueT/PolyGlot#637]
The search interface crashes repeatedly and can only be recovered by exiting and restarting the program. I can't figure out a consistent trigger for it, but if I do I'll comment here to help you find how to fix it.

**Comment by DraqueT** [comment]
Heyo! Thank you for taking the time to report the bug! 

This is actually one that was reported a little while ago and I have since corrected. It's going to be a bit until I release the next version of PolyGlot, so if it's giving you a lot of trouble, let me know and I can hook you up with a beta version that has the problem corrected. Gonna close the ticket now, but feel free to contact me at draquemail@gmail.com. :3
