### ISSUE TITLE
Phonology Output-Input Issue

### ISSUE THREAD

**Issue by Fcomega121** [DraqueT/PolyGlot#656]
hello draque! it's me again. this time I've found a bug in 'phonology & text',
well when I've added the Apostrophe to be read as a Glottal stop, everything seem to work fine,
but when I try'd to add ejective consonants everything went.. strange:
![polyglot issue 2 01 2](https://user-images.githubusercontent.com/46006628/51567429-cb692180-1e5c-11e9-97d2-73ea4d3857ba.png)
I think this is a bug because it happened before when I try'd this:
h > x
x > k͡s
-h = k͡s

**Comment by DraqueT** [comment]
Thank you for the heads up! The next version is in the works and a fix for this will be in there for sure! :3

And again, the visuals are always appreciated.

**Comment by Fcomega121** [comment]
You're welcome and thank you too! :3

**Comment by DraqueT** [comment]
Heyo! Just wanted to get back to you with an answer here. So the problem you have there isn't actually a bug (also, I can tell you how to fix what you're seeing).

You've run into the priority system. The priority of the text replacements when creating the pronunciation is the order in which they appear in the list. You'll need to move the one to a higher priority than the other. This can be done by selecting it, then using the up and down arrows that are to the right of the list.

Let me know if this solves your problem or if I'm missing something. If I'm missing something, please give me an example of a word, its proper pronunciation text, and the pronunciation text that's being produced.

**Comment by DraqueT** [comment]
Ok, could you send me the language file you are working on so that I can observe this directly? My email is draquemail@gmail.com.

Also, in the email, please give me an example of one of the words which is showing its pronunciation wrong and the correct way that it should be displaying. (I know you have given some examples already, but just want to make certain that I'm looking at the right thing).

I'm having trouble reproducing this, and I think that there might be some specific setup in your language that PolyGlot is handling incorrectly. I definitely want to correct this bug for you before the next release. :)
