### ISSUE TITLE
Allow for filtering of conjugation rules on class

### ISSUE THREAD

**Issue by luepola** [DraqueT/PolyGlot#688]
ISSUE TEXT:

Conjugation rules should filter on class as well as other values.

ORIGINAL USER TEXT:
Hello,

Is there a method or feature that is already available that allows for separate conjugation systems to be applied to different traits of a word? In my case, I have a Slavic-based language, where the past tense of a verb conjugates according to gender as opposed to the present conjugation to the person (1st/2nd/3rd). However, I seem to be unable to implement this, as adding a gender conjugation class forces all other conjugations (so far- tense, number, person) to also be split into separate genders, which is counter to how the language works.

Thanks in advance, I am new to this program

**Comment by scottgit** [comment]
Draque may have a better idea than I, but let me take a stab at an answer. If I follow you correctly, a past tense _adds_ gender (and conjugates by that rather than by person), whereas present tense just has number and person (and conjugates by person). What is not clear to me is if person is also part of past tense, just not a factor in conjugating. So a few possible answers as the program currently stands might be (I think it would be an enhancement to allow what you are seeking for):

1. To my knowledge, there is no clear way to separate conjugation rules _other than forming two distinct parts of speech_. This would mean separating your verbs by tense at the basic level under the "Part of Speech" setup. That is, instead of making a "Verb" (Part of Speech) having "Present" and "Past" dimensions to a "Tense" conjugation value, you might make two parts of speech, "Past Verb" and "Present Verb," so that the Past Verb can have the gender value added into the conjugation and the Present Verb does not. **However, the problem here will be that I assume you want a single lexical entry for a verb, and as such, only one part of speech can be added to a lexical entry. This would require two lexical entries of the same "word." _So not an ideal way to split it_.**
2. If person is **_not_** relevant to past tense, only present tense, then in your conjugation setup _combine_ them into a Person/Gender category, with dimensions that cover both ideas, but only the person dimension will apply to present tense verbs and only the gender dimension apply to past tense. E.g. your dimensions might be: 1st, 2nd, 3rd, Male, Female, Neuter. This allows you to only pick one per tense, of which you would pick person with present and gender with past. If you do an "autogeneration" of forms, then for all present tense you would "Disable Wordform" for gender values and for all past tense you would "Disable Wordform" for all person values.
3. If person is **_also still relevant_** to past tense, and you dislike #1 idea, then you still have two options. **First**, you could still do #2, but instead you would need some combination values for your past tense: 1st, 2nd, 3rd, 1stMale, 2ndMale, 3rdMale, 1stFemale, etc. Or **second**, keep your conjugation values for Person and Gender separate, but make one of your Gender dimensions to be "NULL" or "N/A" (not applicable) and then use that dimension for all Present tense words, only using the actual Gender categories for the Past tense words. This still makes clear that the language ignores any Gender idea for Present tense, even though the "category" of Gender is still showing for that tense.

For the record, I could see the value (especially in this case you give) of having the flexibility to have differing conjugation "sets" for the same part of speech, so that the program could define:

Part of Speech: Verb

- Conjugation Set 1 (Use when Key Conjugation is set to dimension Any except Past): Tense (Key Conjugation), Number, Person
- Conjugation Set 2 (Use when Key Conjugation is set to dimension Past): Tense (Key Conjugation), Number, Person, Gender (or Tense, Number, Gender?)

So in my idea here, it allows a particular conjugation value (in this case, Tense) to be the "key conjugation" that determines which conjugation "set" a verb uses based on the dimension setting of that key conjugation value. It may be the program could be allowed to have a combination of "key conjugation values" (not just one). Draque would have to answer how difficult this would be to actually program to make an idea like this happen. I don't suspect it is something that would be easy, so not likely something to be done in the near future, but Draque does like new ideas for enhancement, so he may at least file this under a possible future upgrade.

**Comment by DraqueT** [comment]
Heyo! This is something that I have been meaning to get around to for some time, actually! I have changed this to a feature request to allow conjugation rules to also filter on class values. This is one that should have already been implemented a while back, since it's highly relevant to many languages, but it's going to take a bit more coding due to its complexity.

Until it's complete, @scottgit has posted a workaround that will work for you nicely. Once this is implemented, it will be a much simpler operation, though!

Thank you for taking the time to write up a ticket and to ask about this! PolyGlot gets better based on user interactions and suggestions like this. :3

**Comment by luepola** [comment]
Many thanks! In the meantime, I came up with a similar workaround as @scottgit's second suggestion, where I additionally got rid of the tense field entirely (as in my conlang, all other tenses moods etc are handled auxiliary verbs/particles). 

"Conjugation rules should filter on class as well as other values."
As pertaining to my conlang in particular, one of these other values should be a dimension of another conjugation, if possible, as that would be the most straightforward way to handle it.

**Comment by DraqueT** [comment]
After revisiting this, I think that this is something that can be set up easily, and I'm not sure why I didn't realize this earlier. Conjugation rules can be set to All, which will ensure that they are applied to words regardless of class value. For conjugations/declensions that have nothing to do with classes such as gender, leaving rules set to "All" will do what you're looking for.

Sorry for missing this the first time around, and if this is still something that's causing you trouble, reply back here to reopen the ticket!
