### ISSUE TITLE
Problems with importing vocabulary

### ISSUE THREAD

**Issue by Huy-Ngo** [DraqueT/PolyGlot#857]
UPDATE:
External bug. Logged here: Bug in apache commons. Logged here: https://issues.apache.org/jira/browse/CSV-258

On fix: if new version has J9+ module compatibility, remove from injected jars folder and update build script to point to relevant location of pulled file. If no J9+ module compatibility, pull new jar, inject with module info, drop into injection folder, and update build script to reflect this (unless build script only points to injection folder... in which case last step not necessary).

ORIGINAL TEXT:
I'm trying to import my vocabulary from an `.xlsx` file and it shows an import error:

> Check to make certain that column mappings are correct (nothing above max cell value) and that the file is not corrupt:
Index 0 out of bounds for length 0

I converted it to a `.csv` file and it throws an encoding exception (`MalformedInputException`), since I have modified Latin characters (such as á, ç, õ, etc.). If I remove all these modified characters, it imported correctly

**Comment by DraqueT** [comment]
Thanks for reporting this! Could you please send the excel file you're looking to import? That would let me know I am seeing the exact same bug that you're experiencing. My email is draquemail@gmail.com.

I'll be able to link you to a build where this has been corrected once I've tracked down and fixed the problem.

**Comment by DraqueT** [comment]
Also just to be clear, I haven't been able to reproduce this myself, so I'm willing to bet that there is some encoding method that I'm not accounting for since my own system does not produce it.

**Comment by DraqueT** [comment]
Ok. So good news is that I have found a workaround for you. Bad news is that this specific bug is actually in the library that I am using rather than PolyGlot itself. Going to log a ticket there, but in the mean time, here's how you can get around this. 

1) Open up your CSV file in your favorite text editor.
2) hit Save As
3) Save as UTF 8 or 16, but NOT little endian.

For whatever reason, special characters saved with UTF little endian encoding cause it to blow up.

Please let me know if this works for you!

**Comment by Huy-Ngo** [comment]
Thanks. It works now. I think the lib treated the file as corrupt because there is an empty line at the end of the file unless I deleted it manually by a text editor.
