### ISSUE TITLE
Etymology, and words with parents/children

### ISSUE THREAD

**Issue by DraqueT** [DraqueT/PolyGlot#86]
Allow words to have multiple parent words. This will let people make complex heirarchies of word relations, and better manage words that form families.

Additionally, when a word that has child words is modified, alert users to all children nodes under it that are affected. This will allow deep vocabulary construction and reworking with much less effort.

**Comment by DraqueT** [comment]
Consider that many roots may represent deprecated words, or words from alternate languages. Also consider that some words may have roots in the given language. Allow both to be entered as root/parent nodes. For this reason, it must be children that store their parents, as many of the roots will have no actual entry in the lexicon.

Make another class that extends DictNode, which will be RootWord. It will have a few values, but not so many as WordNode. Make a wrapper class that is able to contain either. This wrapper class is what will populate the list representing a word's roots.

Make another filter criteria that filters on a word's roots.

**Comment by dannYves** [comment]
There is also no etymology section to input any words and/or notes in relation to the etymology which were used from an outside source other than a conlang from within the lexicon page.

**Comment by lucymhdavies** [comment]
Yep. Would love a distinction between internal/external etymologies.

Many of the words in my conlang are based on words in real languages, so it would be good to keep track of them.

**Comment by DraqueT** [comment]
To either of @lucymhdavies or @dannYves Do you have ideas of exactly how you would envision this working? Etymological roots are something that I've been really thinking about for a long time, and I want to get it right the first time when I implement it.

The issue that I'm looking at is that both living and dead words can be roots, and most people don't want dead words mucking up their dictionaries.

**Comment by dannYves** [comment]
> Do you have ideas of exactly how you would envision this working?

The way you have the Thesaurus/Lexical Family sounds great with some of the extra tweaking you mentioned earlier in the post. Like lucymhdavies mentioned there appears to be two major types of etymologies in conlanging: "external" and "internal" and they are treated differently, for example "external" etymologies tend to be more for assisting in constructed prototype words (or Proto-Languages) and are used to recreate words from scratch... whereas "internal" etymologies can get much more complicated with root families and rearrangements of syllables and/or phonological protocols. 

> The issue that I'm looking at is that both living and dead words can be roots, and most people don't want dead words mucking up their dictionaries.

In such case maybe somehow adding the ability for a user to choose what gets exported or included in the finalized dictionary. I'm not sure how the application handles this as I have not toyed around with it yet due to my conlang being in its infancy but from what I read it seems like we can export to excell or PDF.  Is there a way of seeing the pre-finalized copy of the lexicon/dictionary from within the app? That way users can see it and then determine what might be included in the final copy versus what is used as "notes" or "hidden texts" specific for recreation of languages. 

Just my two cents on the matter :-) I really like the whole family root thing you described above, sounds extremely interesting and I can't wait to play around with it.

**Comment by lucymhdavies** [comment]
dannYves is thinking along the same lines as me I think. External etymologies are much simpler, and potentially don't even apply to most/many words in the conlang. A simple generic "notes" feature would work for that.

As for dead words in the internal etymology... agreed, that could get pretty complex. In some conlangs, a simple dead/alive flag could be sufficient. And this would likely be the easiest way to add the feature.

Or perhaps Alive/Archaic/Dead might be useful in some places.

So not sure how best to approach it. I suppose make the feature available initially as a simple Alive/Dead flag, but potentially allow users to expand upon available options later?

**Comment by dannYves** [comment]
> dannYves is thinking along the same lines as me I think. External etymologies are much simpler, and potentially don't even apply to most/many words in the conlang. A simple generic "notes" feature would work for that.

I use a lot of external etymologies too though LoL. and sometimes I'll even fuse two or more external etymologies into one... As far as "external etymologies" go I think it would be nice to see it somewhere in a drop down tab or a spot for it, as it is just an integral part of a language as other grammar.  

> So not sure how best to approach it. I suppose make the feature available initially as a simple Alive/Dead flag, but potentially allow users to expand upon available options later?

I think that is awesome :-)

**Comment by DraqueT** [comment]
Heyo! As a heads up, this is finally happening! I'm closing this ticket, as there's a newer one that I'm now using (#459). The comments here are still going to be included in all the suggestions/considerations for the enhancement, though!
