### ISSUE TITLE
"Push to dimension" not working

### ISSUE THREAD

**Issue by Xaneath** [DraqueT/PolyGlot#867]
Hey! I adore this program, really helpful, but when I try to push a conjugation rule to certain dimensions it won't work. I think it's dimensions over 3? I have a thing with 5 dimensions and it works for the first three, but the last two it won't. Delete From dimension is also doing this.
Edit: It's doing it with other things too. I don't see the pattern there.

**Comment by DraqueT** [comment]
Thank you for the vote of confidence! I'm always really happy to hear from
users!

Anyhow, I have rewritten a good bit of the code having to do with
dimensions. There's a strong possibility that the problem has been fixed by
those updates. I think the first thing you should try is the latest beta
build. You can snag that over here:

https://draquet.github.io/PolyGlot/

I just did a fresh build, so there should be brand new copies up and
available as of this morning. Try installing that and pushing. If that
doesn't work then I will definitely open up a ticket and try to track
down/correct this bug!

If you still run into the issue, could you please send me the language file
you're working on and the exact steps to recreate the problem? That will be
the fastest way to get it corrected. Also, I will make sure you have a beta
copy with the fixed bug asap that way.

- Draque

**Comment by Xaneath** [comment]
Just tried downloading the beta... There wasn't an app in the launcher, just a bunch of files?

**Comment by DraqueT** [comment]
Oh shoot, checking this out now... are you on OSX?

- Draque

**Comment by Xaneath** [comment]
Yeah.

**Comment by DraqueT** [comment]
Huh, somehow the website got confused and was pointed at a really messed up
build! I'll have to correct that. In the future, all current builds are
available there. In the meantime, here is a direct link to the newest build:

https://drive.google.com/file/d/1acDGiDMseQfITWncQbL0AkXfDAH9b002/view?usp=sharing

- Draque

**Comment by Xaneath** [comment]
Gah. It won't even let me open that version. Says it's "damaged".

**Comment by DraqueT** [comment]
Whoof, sorry this is running into so many issues. I’ll take another look when I get back. X|

-Draque

**Comment by DraqueT** [comment]
So the good news is that you have helped me to find a massive bug. Java 14
signs all executable images in a way that is new, and seems to only allow
them to be used on the system they're compiled on... the bad news is that
this means it'll likely be a few days before I can get any functioning
builds out.

I appreciate both of the bugs you brought to my attention!

- Draque

**Comment by DraqueT** [comment]
PolyGlot 3.1 has been released as a heads up, and the incompatibility issue you were running into earlier (the one saying the install file was broken) is resolved if you would like to give this another try. I have not been able to reproduce the bug again in the mean time, so I will be closing the ticket for now. You can get the new version at:

https://draquet.github.io/PolyGlot/
