### ISSUE TITLE
Heat Map Of Letter Combinations Hot For "1" Combination

### ISSUE THREAD

**Issue by brunoczim** [DraqueT/PolyGlot#891]
Tools > Language Statistics

[You can download my conlang to test here](https://github.com/brunoczim/ficlangs/blob/20da5adfbcc432bfcbe2e20240e28dd9127cf957/Star%20Folk.pgd).

![image](https://user-images.githubusercontent.com/18701450/80865362-47a50400-8c5f-11ea-907f-477b7ee789db.png)

**Comment by DraqueT** [comment]
Confirmed this bug, thank you for taking the time to report it! :3

**Comment by luispabloherrera** [comment]
Hello, I'm having the same issue. 
Sometimes I can trace it to a specific IPA rule conflicting, but I can't seem to find what the issue is right now.

![Image](https://github.com/user-attachments/assets/1dedaef7-414a-4bc6-b56b-8b062d3447b7)

Language file:
https://github.com/luispabloherrera/Imyask-PolyGlot/blob/main/polyglot_imyask3.pgd

**Comment by luispabloherrera** [comment]
I think it's an html rendering issue, because saving as PDF (from Google Chrome and checking Background Graphics) doesn't have the issue
