### ISSUE TITLE
In check language tool, highlight the letters that are missing.

### ISSUE THREAD

**Issue by le-birb** [DraqueT/PolyGlot#897]
When I'm faced with this:
![image](https://user-images.githubusercontent.com/17369466/81245306-7d344f00-8fc9-11ea-9e65-624bdda98f09.png)
I have a somewhat hard time figuring out what the problem is. Highlighting the unaccounted for letters/problem areas in the word(s) would go a long way to help remedy that.

**Comment by DraqueT** [comment]
This is something I've been considering for quite some time. Due to some languages using symbols which are actually multiple characters, there are some technical difficulties. It's something I'm absolutely puzzling over, though.

In the mean time, if you do Tools->Check Language, it will show you the words which contain unaccounted for characters. Not a perfect solution, but at least a workaround for now.

**Comment by le-birb** [comment]
My screenshot has the check languages tool open and showing a problem word, but I had a lot of trouble figuring out which character was the problem. (It was a ’ versus a '), and especially with the long words in this particular language and a large symbol set, it was very difficult to figure that out given only a word and that something's wrong, but no hints as to what.

As for the multi-character symbols thing, what kind of issues do those create?

**Comment by DraqueT** [comment]
I sat down and puzzled over this one and think that I have a solution that corrects for 99% of cases!

**Comment by DraqueT** [comment]
If you want to check the new feature out, the latest beta build includes it at: https://draquet.github.io/PolyGlot/
