### ISSUE TITLE
Request: Portable distribution

### ISSUE THREAD

**Issue by curiosity-a** [DraqueT/PolyGlot#917]
Any chance of portable (or otherwise without an installer) distributions? Especially relevant for the Linux distribution, which is a package right now and thus would necessarily become controlled by the package manager on installation.

**Comment by DraqueT** [comment]
There doesn't currently exist one, but that's an interesting idea! I would probably want to pull some of the integrations... gotta think over exactly how I would offer this, since I do multiplatform releases.

**Comment by Merovius** [comment]
I would like to second this. Users with a Linux distribution that is not derived from Debian (I'm on Fedora, for example) would also benefit from this. Currently, they have to build from source or unpack the `.deb` and hope they can put everything at the right place :)

**Comment by Jade-TheCat** [comment]
Way later on this, but since the project is in Java, surely you could bundle it as a JAR for distribution? That would work on every platform as long as you have Java installed. I would recommend looking at something like [this guide](https://www.baeldung.com/executable-jar-with-maven), particularly the One Jar option, provided all the dependencies are allowed to be distributed. I'd be willing to figure this out and submit a PR if that would make things smoother!

**Comment by Jade-TheCat** [comment]
Ok so I mentioned the One Jar option, but that isn't actively maintained so I'd instead recommend the Maven Shading option. That said, I have tried it and it seems to work, apart from a few weird things related to the assets (specifically the version file), and the docs aren't included so the whole way that is done would need to be reworked. I'm sure that wouldn't be that hard, though

**Comment by DraqueT** [comment]
Heyo! There actually _is_ an alpha PolyGlot build for Android out there! Check it out at the link below!

https://github.com/pe1uca/PolyGlot

**Comment by curiosity-a** [comment]
What does Android have to do at all with this? Can you give a coherent explanation why you are suddenly closing this issue without an obvious resolution?

**Comment by DraqueT** [comment]
While I am reopening this, I would like to politely remind you that you are not the manager of open source coders. That's a fairly demanding and accusatory tone you're taking on a project that is not your own.

That having been said, I'm reopening this, as I blearily mistook "portable" to mean "phone version" the other day. As a current workaround, if you install PolyGlot to a thumb drive, it should still function if you plug that in elsewhere.

**Comment by curiosity-a** [comment]
I am not trying to manage you, but I do believe it a common courtesy to explain beyond the obvious why you are closing an issue, even only insofar as to save yourself the trouble of me or someone else simply reposting the issue again.

That said, I may have been too hasty with making assumptions about your intent there, so sorry about that.

**Comment by Jade-TheCat** [comment]
I suppose I should have clarified: Portable here means platform-agnostic, hence recommending a JAR, which would work on any system with Java installed (this is how Minecraft Java was distributed for Linux and Mac for years). This could save the requirement to build for all Linux distros (currently you only distribute for Debian) or choosing flatpak, appimage, or snap for distribution.

I'll change the title to be a bit more clear, saying platform-agnostic rather than portable.

**Comment by synthfi** [comment]
closing this issue in favor of continuing discussion on other existing issues. FWIW, the latest release has added linux RPM packages for x86 and apple silicon. lmk if they don't work

- portable installation request: https://github.com/DraqueT/PolyGlot/issues/1278
   - I need to think about this some more
- request for flatpak: https://github.com/DraqueT/PolyGlot/issues/1348. I am trying to work on this for 3.7
- please continue discussion on android here: https://github.com/DraqueT/PolyGlot/issues/1361
   - not actively in development for now though
