### ISSUE TITLE
Response to Issue #922 :)

### ISSUE THREAD

**Issue by SgtMorocco** [DraqueT/PolyGlot#925]
This message was originally commented under the prior closed issue (#922 ), I am new to github and have no idea how to open issues, and I did read the intro page, but all the help pages I found were a step above my issue and I found confusing, maybe I just missed it? 

Anyway, Message was as such:

Sorry about taking so long! I'm new to github and hadn't recieved an Email notif til today.

The problem with the É and A is that one word was like this: Éþanst and after the vowel change it would become: Aþénst. The program seemed to be able to swap the A to an É but didn't swap the É to an A.

Also if it helps the infinitve form of the verb is one column to the left of the highlighted box in the first image.

Edit: Also, is there a way of including words from other polyglot language files without typing them in manually? As in: I have a proto-language parent of my main language in a separate PolyGlot file, is there a way of taking the words (and potentially etymologies) from files and adding them to trees in other files.

**Comment by DraqueT** [comment]
Ok!  I think I see the issue here. You have a rule that changes É->A, then another rule that changes A->É. Basically it's just changing one way, then changing back again. If you want to SWAP them, you'll need to make two separate rules.

The first rule should have a regex filter (the field below the rule name) of "^É.*" and change É->A. The second rule should have a regex filter of "^A.*" and change A->É.

Please let me know if this helps you, and sorry for taking a bit to get back to you!
