### ISSUE TITLE
Would be nice to be able to sort the lexicon by date

### ISSUE THREAD

**Issue by ClemCa** [DraqueT/PolyGlot#935]
Hi
Sometimes, I just wonder what was the last thing I worked on, or what were the last added words. It'd be nice to be able to use such a feature. It's better than skimming through every word one by one to compare it with a backup. I know it implies probably changing a bit the save format, so don't bother with it if it's a hassle.
Have a nice day.

**Comment by DraqueT** [comment]
Heyo! Thank you for the suggestion here, but it's unfortunately not possible for me to organize entries like this due to PolyGlot's internal structure. You might consider creating a lexical class that defines words as "new" though, so you could know what's still being worked on?

Also, sorry for taking a long time to get back to you! I was pulled away from this project pretty hard over the last few months.

**Comment by ClemCa** [comment]
It's fine. thanks for letting me know
