### ISSUE TITLE
What is wrong with my regex?

### ISSUE THREAD

**Issue by Rially** [DraqueT/PolyGlot#969]
Hello, I was working on my auto declensions, and I used this regex:
`(s(?=_))(?(1)|s$)`

And the error is "Unknown inline modifier near index 10"
I tested it on [regex101.com](https://regex101.com/), and it seems to work there.
It should match
yall**s**
act**s**_ the
smeccen**s**_ thos
han_ troo**s**

Like: match s followed by _; if no match, match finishing s
I am not sure why it is not working.

**Comment by DraqueT** [comment]
The issue you're running into there has to do with the group conditional
feature, which exists in perl regex (what Regex 101 runs on), but not Java
regex (which PolyGlot runs on). That limitation can be a bit frustrating,
but it's also why PolyGlot supports multiple rules with filters. What you
can do is break this into two transformations. The first is:

pattern: s(?=_.*[^s$])


That will snag the first instance of s followed by _ in  words that DO NOT
end in an s.
The second is a filtered transform:

filter: ^((?!s_).)*$
pattern: s$

The result of this is that it will replace a trailing s, but ONLY for words
that do not contain the pattern "_s". Below are screens of how this should
look. Remember that in the second, the filter must be set so that it is not
applied to all trailing s instances.

[image: image.png]
[image: image.png]

Hope this helps!

- Draque
