### ISSUE TITLE
IPA conversion tool converts whole HTML string

### ISSUE THREAD

**Issue by le-birb** [DraqueT/PolyGlot#989]
I was today wanting to get the pronunciation of a name I had made in a language, so I loaded up polyglot to use the IPA conversion tool. I entered my name in it, and got
![image](https://user-images.githubusercontent.com/17369466/125007810-f4be9d80-e015-11eb-9e5a-1bf40e5c8b02.png)
which while it _does_ give me the name's pronunciation, is evidently not how it is supposed to work.

**Comment by le-birb** [comment]
Digging through the code a bit, it looks like PTextPane.getNakedText() is for some reason not properly stripping out the HTML from the string it grabs, which leads to the mangled output there.

**Comment by DraqueT** [comment]
Heyo! Thank you for doing some digging here! I am pretty sure that this is a bug that I've fixed in the newest beta. You can find that over here if you want to give it a download: https://draquet.github.io/PolyGlot/

I will mess around with this a bit though to make sure there's nothing lingering. If the beta still gives you problems let me know and I'll get it working for you. :)

**Comment by le-birb** [comment]
I have tested it, and it is indeed fixed!
